version: '3'

services:
    server_standalone:
        image: lanrat/ct
        volumes:
            - server1:/data
            - ./keys:/data/keys:ro
        environment:
            - TZ=America/Los_Angeles
        ports:
            - 6962:6962
        command: ct-server --key=/data/keys/privkey.pem --trusted_cert_file=/data/keys/ca-roots.pem --leveldb_db=/data/leveldb/ --i_know_stand_alone_mode_can_lose_data --colorlogtostderr --logtostderr --guard_window_seconds=5 --tree_signing_frequency_seconds=10


    server:
        image: lanrat/ct
        volumes:
            - server:/data
            - ./keys:/data/keys:ro
        environment:
            - TZ=America/Los_Angeles
        ports:
            - 6962:6962
        command: ct-server --key=/data/keys/privkey.pem --trusted_cert_file=/data/keys/ca-roots.pem --leveldb_db=/data/leveldb/ --i_know_stand_alone_mode_can_lose_data --colorlogtostderr --logtostderr --guard_window_seconds=5 --tree_signing_frequency_seconds=10 --etcd_servers=etcd:4001
        depends_on:
            - etcd


    server1:
        image: lanrat/ct
        volumes:
            - server1:/data
            - ./keys:/data/keys:ro
        environment:
            - TZ=America/Los_Angeles
        ports:
            - 6962:6962
        command: ct-server --key=/data/keys/privkey.pem --trusted_cert_file=/data/keys/ca-roots.pem --leveldb_db=/data/leveldb/ --colorlogtostderr --logtostderr --guard_window_seconds=5 --tree_signing_frequency_seconds=10 --etcd_servers=etcd:4001
        depends_on:
            - etcd


    server2:
        image: lanrat/ct
        volumes:
            - server2:/data
            - ./keys:/data/keys:ro
        environment:
            - TZ=America/Los_Angeles
        ports:
            - 6963:6962
        command: ct-server --key=/data/keys/privkey.pem --trusted_cert_file=/data/keys/ca-roots.pem --leveldb_db=/data/leveldb/ --colorlogtostderr --logtostderr --guard_window_seconds=5 --tree_signing_frequency_seconds=10 --etcd_servers=etcd:4001
        depends_on:
            - etcd


    etcd:
        image: lanrat/ct-etcd
        volumes:
            - etcd_data:/opt/etcd/data
        hostname: etcd
        environment:
            - TZ=America/Los_Angeles


    mirror:
        image: lanrat/ct
        volumes:
            - mirror:/data
            - ./keys:/data/keys:ro
        environment:
            - TZ=America/Los_Angeles
        ports:
            - 6964:6962
        command: ct-mirror --leveldb_db=/data/leveldb/ --i_know_stand_alone_mode_can_lose_data --colorlogtostderr --logtostderr --target_public_key=/data/keys/pubkey.pem --target_log_uri="http://triton.vorsk.net:6962/"


    mirror_remote:
        image: lanrat/ct
        volumes:
            - mirror2:/data
        environment:
            - TZ=America/Los_Angeles
        ports:
            - 6965:6962
        command: ct-mirror --leveldb_db=/data/leveldb/ --i_know_stand_alone_mode_can_lose_data --colorlogtostderr --logtostderr --target_public_key=/usr/local/etc/keys/digicert_ct1.pem --target_log_uri="https://ct1.digicert-ct.com/log"


volumes:
    server: {}
    server1: {}
    server2: {}
    mirror: {}
    mirror2: {}
    etcd_data: {}
